### ISSUE TITLE
Sorting remote branches by date not working

### ISSUE THREAD

**Issue by jryom** [sodapopcan/vim-twiggy#14]
First of all thanks for the great work on this plugin, really love using it.

I can't seem to get sorting of the remote branches to work. For local branches, changing the sorting method works as expected, but for remote branches the sorting method makes no difference.

<img width="134" alt="screen shot 2018-07-05 at 15 43 53" src="https://user-images.githubusercontent.com/2834949/42326762-6320a836-806a-11e8-9f5b-2b60f1da47e7.png">
<img width="149" alt="screen shot 2018-07-05 at 15 43 40" src="https://user-images.githubusercontent.com/2834949/42326763-633d5436-806a-11e8-8321-fbf89f527643.png">

**Comment by sodapopcan** [comment]
D'oh, thanks for letting me know!  I will look into this tonight.

Thanks for the kind words :)

**Comment by sodapopcan** [comment]
Was able to fix it at lunch... shooooould be good!
