### ISSUE TITLE
Add space between icons

### ISSUE THREAD

**Issue by kristijanhusak** [sodapopcan/vim-twiggy#15]
Hi,

is there a way to add to add a space between icons? It looks a bit to narrow for me.

I tried adding custom icons with the space, but it gets ignored:

```vimL
let g:twiggy_icons = ['* ', '✓ ', '↑ ', '↓ ', '↕ ', '∅ ', '✗ ']
```

**Comment by sodapopcan** [comment]
Unfortunately, there is some logic coupled to the UI making this a non-trivial change.  I'm not actually feeling this pain myself and don't have the time to put into it right now.  I'll have some time in a couple of months if it's still an issue for you.

Thanks for the feedback and using the plugin!

**Comment by kristijanhusak** [comment]
Ok, thanks.

**Comment by sodapopcan** [comment]
No need to close this, I've actually been thinking about it, just no time to dig into it right away!

**Comment by kristijanhusak** [comment]
Ah, ok. I figured out that i'm not really using the plugin so much, so i removed it. Thought it's ok to close it if no one else has the issue with it.

**Comment by sodapopcan** [comment]
Oh, haha, well then!  I won't bother :)
