### ISSUE TITLE
Autocmd Event

### ISSUE THREAD

**Issue by weilbith** [sodapopcan/vim-twiggy#16]
I'd like to establish an autocommand when the `twiggy` buffer get opened. Unfortunately I can't find an event that gets thrown to do so. As file pattern I use `*` cause it feels easier to check for the filetype. Anyways, if I add an `autocmd` without any filter which just use `echom` and try it for all event listed in `h autocmd-events`, I never get an entry after open `:Twiggy` when I have a look at `:messages`. I'm confused about this. What am I doing wrong?

**Comment by sodapopcan** [comment]
Does the `FileType` event not work for you?

```viml
autocmd FileType twiggy echom "Twiggy open"
```

**Comment by weilbith** [comment]
Oh damn. That was something I could know/tried. :see_no_evil: 
Sorry for wasting your time and thank you very much!

**Comment by sodapopcan** [comment]
Hey no, prob—we're all learning here!
