### ISSUE TITLE
suggestion: add some screenshots / animated gifs to README

### ISSUE THREAD

**Issue by lavie** [sodapopcan/vim-twiggy#2]
I just think it would go along way towards getting people to try it out. Great project, BTW.

**Comment by sodapopcan** [comment]
Honestly the main reason I didn't do this (and also applies to #1 as well, heh) is, being a fugitive extension, I was constantly asking myself, "Would tpope do this?", hehe.

I'm actually not opposed to this at all _but_ I've actually never done such a thing and would have to think about it.  I'd certainly accept a PR for a nice one.

**Comment by joereynolds** [comment]
Another alternative is opening an issue that is screenshots/gifs so you don't clog your plugin :)

**Comment by sodapopcan** [comment]
Not a bad idea!  Though I’m honestly not opposed to having one in the README, I just haven’t been thinking too much about it so far.

**Comment by sodapopcan** [comment]
Oooook, so for now I've added one screenshot (9e53916df8eb63a207a4c35186e9b9ad5c7c5bcc).  It obviously doesn't show off everything, but I've never made a screen or ascii cast before and it's very time consuming.  Will undoubtedly be a bit before I get to it but I hope this shows it off well enough.

**Comment by sodapopcan** [comment]
@lavie I just reread through this issue... not sure where my manners were (or was more focused on the first part of the issue) but:  Thank you for your kind words!
