### ISSUE TITLE
Branch overview and quick help don't hide all line numbers

### ISSUE THREAD

**Issue by zappolowski** [sodapopcan/vim-twiggy#23]
My usual setup runs in hybrid mode (using the wording used in [this blog post](https://jeffkreeftmeijer.com/vim-number/)), which causes the branch overview as well as the quick help window to switch to pure relative mode. Within quick help this also causes the lines to be truncated.

Though it's easy to work around this, it might be appropriate to disable `relativenumber` as well. This is done e.g. in fugitive's blame window, NERDTree and DeFx (just searched for some plugins which create conceptually similar windows) already.

**Comment by sodapopcan** [comment]
Thanks for pointing this out!
