### ISSUE TITLE
Square brackets in commit message breaks detecting remote

### ISSUE THREAD

**Issue by kristijanhusak** [sodapopcan/vim-twiggy#25]
Hi,

I noticed that Twiggy cannot properly detect remote when commit message contains square brackets.

For example, for my projects, i prefix all commit messages with jira ticket name:
```
[MP-123] Fix reports.
```

This causes twiggy to set `MP-123` as a remote, which causes push failures with message:

```
Remote does not exist 
```

**Comment by sodapopcan** [comment]
Ah yes, that makes sense.

I'm not going to be able to get to this for a few days.  If you're viml savvy and feel like sending a PR, it very likely has to do with this section: https://github.com/sodapopcan/vim-twiggy/blob/master/autoload/twiggy.vim#L199-L203.  Otherwise, I'll try and get to it later in the week.

Thanks for the report!

**Comment by kristijanhusak** [comment]
I have idea how to solve it, but no enough time to dedicate myself to it.
Using custom format when listing branches, something like this:

```
git branch -vv --no-color \
--format="%(HEAD)!!>><<!!%(objectname:short)!!>><<!!%(refname:short)!!>><<!!%(subject)!!>><<!!%(push:remotename)!!>><<!!%(upstream:track)"
```
later splitting it by `!!>><<!!` would give us everything that we need to generate a branch dictionary. Not sure what to use for delimiter, this is really ugly, but i assume it won't happen in commit message. I maybe missed something, but the general idea is here.

**Comment by sodapopcan** [comment]
So I finally sat down to take a look.  I actually thought it was going to be easier than it is and your solution is actually very helpful!  I will try and fix this weekend.  Sorry for the delay!

**Comment by sodapopcan** [comment]
I ended up using a double-tab as a delimiter—I figure that is pretty damn safe.

**Comment by kristijanhusak** [comment]
Works like a charm! Thanks!
