### ISSUE TITLE
Twiggy always opens on the right no matter value of twiggy_split_method

### ISSUE THREAD

**Issue by dbatten5** [sodapopcan/vim-twiggy#37]
I've tried all four possible values for `twiggy_split_method` and the window always opens on the right. I've been able to control other aspects of the twiggy window fine, eg. the number of columns with `let g:twiggy_num_columns = 50`.

![image](https://user-images.githubusercontent.com/17271241/98176941-74c5be00-1ef1-11eb-8e40-7f10aba4dba1.png)

I've echoed out the value of `g:twiggy_split_method` which is `topleft` and as you can see the window is on the right. Is there something else I'm missing? Or perhaps a conflicting configuration variable? A bit stuck on where to start debugging this. 

If I open a new split with eg `:topleft vnew` it works as expected.

Thanks!

**Comment by sodapopcan** [comment]
Do you have `splitright` set?  (`:echo &splitright` => `1`).  That's how I'm able to reproduce this.

**Comment by sodapopcan** [comment]
Ok, upon further inspection, `twiggy_split_method` is documented but never used 😬😬😬  Clearly a bug.

**Comment by sodapopcan** [comment]
Sooooo, it turns out that the documentation was just wrong.  The setting is actually `g:twiggy_split_position` 🤦   I've fixed the docs.

**Comment by dbatten5** [comment]
Ah great, probably should have checked that myself! Thanks for updating though
