### ISSUE TITLE
Add a doautocmd User TwiggyCheckoutCommand in s:Checkout() ?

### ISSUE THREAD

**Issue by mckellygit** [sodapopcan/vim-twiggy#45]
Hi,
Thank you for vim-twiggy.  Just a suggestion here.
I've added this to help me know when to refresh some other things and I was wondering if you could add it or something like it also ?  I can create a PR if you like.
In s:Checkout() and s:CheckoutAs() when switching branches can we issue a User autocmd so other plugins can know this ?
I added this line in these two routiunes before returning -
```
  doautocmd User TwiggyCheckoutCommand
```
thx,
-m

**Comment by sodapopcan** [comment]
Hi!  This isn't something I'd be interested in for myself and my focus is elsewhere right now, so it would be a while before I would get to doing it myself.  But I'm more than happy to merge a PR if you submit one!

**Comment by mckellygit** [comment]
ok, thanks.  I will submit a PR very soon.

**Comment by mckellygit** [comment]
Hi,
PR added - https://github.com/sodapopcan/vim-twiggy/pull/46
thx

**Comment by mckellygit** [comment]
Closing this issue as the PR as been merged.
