### ISSUE TITLE
Misspelled setting in docs 

### ISSUE THREAD

**Issue by davidklsn** [sodapopcan/vim-twiggy#8]
In the docs it says that `let g:twiggy_num_colums` is used to set buffer width but the correct usage is `let g:twiggy_num_coloumns`

**Comment by sodapopcan** [comment]
Oh my, that's embarrassing!  I assume since you didn't submit a PR that you'd rather I fix it—ie that you don't want the commit credit?

**Comment by sodapopcan** [comment]
Meh, I just fixed it.  Thanks a lot for reporting it!

**Comment by sodapopcan** [comment]
PS, I actually renamed the variable to the proper spelling.  I figured it's only a minor annoyance to the one or two people who have actually used this setting so far.

**Comment by davidklsn** [comment]
Sorry for a late response!

No problem! thanks for a great plugin!
